name: Generate Contribution Graph

on:
  push:
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from (**required**).
          # Use action context variable `github.repository_owner` or specify a user directly.
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate, each on a new line.
          # Customize each output with query string options.
          #
          # Supported options:
          # - palette:     Preset color scheme. Choices are [github, github-dark, github-light].
          # - color_snake: Color of the snake.
          # - color_dots:  Comma-separated list of dot colors. 
          #                The first color represents 0 contributions, with the remaining colors indicating increasing contributions.
          #                Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
